FROM node:12-alpine as builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build:prod

FROM node:12-alpine
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --production

COPY --from=builder /app/.compiled ./.compiled

EXPOSE 3000
ENTRYPOINT ["npm", "start"]
